/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#3d4947",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "surface-container-high": "#e2e7ff",
        "on-primary-container": "#f4fffc",
        "on-tertiary-fixed": "#341100",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#783200",
        "secondary-fixed": "#cce5ff",
        "tertiary-fixed": "#ffdbca",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ffb690",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "error": "#ba1a1a",
        "surface-container": "#eaedff",
        "tertiary-container": "#c05400",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#93ccff",
        "on-secondary-fixed-variant": "#004b73",
        "on-surface": "#131b2e",
        "inverse-primary": "#6bd8cb",
        "surface-dim": "#d2d9f4",
        "surface-container-highest": "#dae2fd",
        "secondary-container": "#5bb8fe",
        "inverse-surface": "#283044",
        "tertiary": "#994100",
        "surface": "#faf8ff",
        "background": "#faf8ff",
        "surface-tint": "#006a61",
        "primary-container": "#008378",
        "on-error-container": "#93000a",
        "outline": "#6d7a77",
        "surface-bright": "#faf8ff",
        "primary-fixed-dim": "#6bd8cb",
        "on-secondary-container": "#00476e",
        "secondary": "#006398",
        "primary-fixed": "#89f5e7",
        "surface-variant": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "on-background": "#131b2e",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001d31",
        "on-primary-fixed-variant": "#005049",
        "outline-variant": "#bcc9c6",
        "primary": "#00685f",
        "on-primary-fixed": "#00201d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "container-max": "80rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "margin-mobile": "1rem",
        "space-3xl": "4rem",
        "space-xs": "0.5rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "gutter-tablet": "1.5rem",
        "space-2xl": "3rem",
        "space-xl": "2rem",
        "gutter-mobile": "1rem",
        "gutter-desktop": "2rem",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      fontSize: {
        "display": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "display-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
